version: "3.8"
services:
  api:
    image: "${IMAGE_NAME}"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - ./files:/app/files
    command: /bin/sh -c "prestart.sh"
